spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/test
#    username: user
#    password : 1234
#    driver-class-name: org.h2.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: none # 자동 테이블 생성
    properties:
      hibernate:
        format_sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false # 배포 시 true

logging:
  level:
    org.hibernate.SQL: debug # JPA가 생성하는 모든 SQL 로그가 보임
    org.hibernate.type : trace # 요청 파라미터값 출력
server:
  port: 8080
