spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: user
    password : 1234
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create # 자동 테이블 생성
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    org.hibernate.SQL: debug # JPA가 생성하는 모든 SQL 로그가 보임